#!/bin/bash

echo  `pkg-config --cflags --libs opencv` 
echo ""
echo ""
echo ""

#g++ grabber.cpp  -o grabber `pkg-config --cflags --libs opencv` 

#g++ grabber.cpp  -o grabber  -I/usr/local/include/opencv -I/usr/local/include -L ~/opencv/build/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_viz -lopencv_core


g++ grabber.cpp  -o grabber -I ~/opencv/include  -L ~/opencv/build/lib  -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_viz -lopencv_core

